### ISSUE TITLE
Prior art

### ISSUE THREAD

**Issue by alphapapa** [bgturner/emacs-sandbox#2]
Hi,

Are you familiar with https://github.com/alphapapa/emacs-sandbox.sh ?  If you would, please consider renaming this script in some way to avoid confusion.

**Comment by bgturner** [comment]
Hi! I wasn't aware of your script, it looks pretty cool and approaches the idea of creating Emacs sandboxes in a different way -- thanks for releasing it on Github!

To me, the term sandbox is a pretty generic term for a place to mess around and try things which is why I used that word in the name of this script. Since this repo isn't really being consumed anywhere publicly except for curious minds here on Github, is there anything really confusing about having both repositories with similar names? 

Users can see alphapapa's `emacs-sandbox.sh` script as well as bgturner's `emacs-sandbox.sh` script. In an ideal world, they inspect both repos and take the best approaches from each script and create their own `emacs-sandbox.sh` script. Doesn't that sound like a beautiful, open-source world?

**Comment by alphapapa** [comment]
>  In an ideal world, they inspect both repos and take the best approaches from each script and create their own emacs-sandbox.sh script. Doesn't that sound like a beautiful, open-source world?

Not exactly.  I'm trying to make my script a standard, generally useful one so people don't have to make their own, because doing so takes hours of work, trial-and-error, testing on different Emacs versions, etc.  When I see people asking about how to run Emacs in different configurations, I link to my script, which solves the problem in, hopefully, the best way.  I've been working on it and recommending it for almost two years now.  It's not intended to be just an inspirational example.

So now when people search for "emacs sandbox," they're as likely to find your less featureful, less flexible script as they are to find mine, and they won't realize that they are two very different things, and they'll likely not examine both of them; and in that case, they'll miss out on a potential solution to the problem of easily running Emacs in arbitrary configurations.
